# Site settings
title: Live Distributed
email: duobrien@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A "random" blog of the things that interest me in technology including DevOps, Cloud, IoT, Home Automation, STEM Youth Enrichment, and probably a few more along the way.  It it seems like a hodgepodge of a mess, welcome to my world!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://livedistributed.com" # the base hostname & protocol for your site
twitter_username: dustinobrien
github_username:  dustinobrien

# Build settings
markdown: kramdown
